In [1]:
import numpy as np

class LeeBrickellISD():
    
    def __init__(self, H, syndrome, t):
        self.H = H
        self.syndrome = syndrome
        self.t = t
        self.max_iterations = 100
        
    def generate_random_permutation(self, n):
        P = Permutations(n).random_element().to_matrix()
        return P
    
    def get_weight(self, e):
        """
        Returns the weight of the error vector
        """
        weight = 0
        for ei in e:
            if ei != 0:
                weight += 1
        return weight
     
    def perform_attack(self):
        while True:
            r, n = self.H.dimensions()
            while True:
                P = self.generate_random_permutation(n)
                H_new = self.H * P
                # block_matrix - concatenating submatrices (rows first, then columns)
                # H_new | I_r (identity matrix placed to the right)
                H_new = block_matrix(1, (H_new, identity_matrix(r)))

                RREF = H_new.rref()
                U = RREF[:, n:n+r]
                V = RREF[:, r:n]
                W = RREF[:, 0:r]
                if W != identity_matrix(r):
                    break

            s = U * self.syndrome
            s = s.transpose().list()
            k=n-r
            

            p =2
            for j in range(0, binomial(p,k)):
                print(p,Combinations(range(k),p).list())
                I = (Combinations(range(k),p).list())[j]
                print(I)
                print(s)
                print(sum([V.column(i) for i in I]))
                print(np.add(s,sum([V.column(i) for i in I])))
                #s=[1, 1, 0, 0, 0, 0]
                #aux=(1, 1, 1, 0, 0, 0)
                if self.get_weight(np.add(s,sum([V.column(i) for i in I]))) == self.t - p:
                #if self.get_weight(np.add(s,aux)) == self.t - p:
                    print("Hello")
                    a=np.add(s , sum([V.column(i) for i in I]))
                    #a=np.add(s , aux)
                    a=a.transpose().tolist()
                    error=a+[0] * k
                    for i in I:
                        error=np.add(error,[0]*i + [1] +[0]*(r+k-1-i))
                    break  
            if self.get_weight(error)==self.t:
                return Matrix(error)* P.T


                
    def check_property(self):
        nr_iter = 0
        max_iter = 10
        while True and nr_iter < max_iter:
            error = self.perform_attack()
#             print("-----")
#             print(self.H * error.transpose())
#             print("~~~~~~~~")
#             print(self.syndrome)
#             print("----")
            if self.H * error.transpose() == self.syndrome:
                print("correct: ", error, self.H * error.transpose())
                return error, self.H * error.transpose()
                break
            if nr_iter == max_iter:
                print("maximum iterations")
                break
            nr_iter += 1
            

n = 8
# H: an r × n binary parity-check matrix
# matrix generated using goppa code in sage using jupyter notebook
H = Matrix(GF(2), matrix([[1, 0, 0, 0, 0, 0, 0, 1],
[0, 0, 1, 0, 1, 1, 1, 0],
[0, 1, 1, 1, 0, 0, 1, 0],
[0, 1, 1, 1, 1, 1, 1, 1],
[0, 1, 0, 1, 1, 0, 1, 0],
[0, 0, 1, 1, 1, 1, 0, 0]])) # 6 x 8

# s: an r-bit long syndrome (column vector)
syndrome = Matrix(ZZ, matrix(6, 1, [0, 1, 1, 0, 0, 1]))  
# t: the weight of the error vector to be recovered
t_weight = 3

#Output: e: an n-bit binary row error vector s.t. H*e^T = s, with WEIGHT(e) = t

leeBrickell = LeeBrickellISD(H, syndrome, t_weight)
# e, _, __ = prange.attack()
# print("OUTPUT:\n", H * e.transpose())

print(leeBrickell.generate_random_permutation(n))
e, prop = leeBrickell.check_property()
e = leeBrickell.perform_attack()

[0 0 0 0 1 0 0 0]
[0 0 0 0 0 1 0 0]
[0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 1]
[0 0 0 1 0 0 0 0]
[0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0]
2 [[0, 1]]
[0, 1]
[1, 0, 0, 1, 0, 0]
(1, 1, 0, 1, 0, 0)
[0 1 0 0 0 0]
Hello
2 [[0, 1]]
[0, 1]
[0, 1, 0, 1, 0, 0]
(1, 0, 1, 0, 1, 0)
[1 1 1 1 1 0]
2 [[0, 1]]
[0, 1]
[1, 1, 0, 0, 0, 0]
(0, 0, 1, 1, 1, 0)
[1 1 1 1 1 0]
2 [[0, 1]]
[0, 1]
[1, 0, 0, 0, 0, 1]
(1, 1, 1, 1, 0, 0)
[0 1 1 1 0 1]
2 [[0, 1]]
[0, 1]
[1, 1, 0, 1, 0, 0]
(1, 1, 0, 1, 0, 0)
[0 0 0 0 0 0]
2 [[0, 1]]
[0, 1]
[1, 0, 0, 0, 1, 0]
(1, 0, 1, 1, 1, 0)
[0 0 1 1 0 0]
2 [[0, 1]]
[0, 1]
[0, 1, 0, 1, 1, 0]
(0, 1, 0, 1, 1, 0)
[0 0 0 0 0 0]
2 [[0, 1]]
[0, 1]
[0, 0, 0, 1, 0, 1]
(1, 1, 0, 1, 0, 0)
[1 1 0 0 0 1]
2 [[0, 1]]
[0, 1]
[0, 1, 1, 1, 0, 0]
(0, 1, 0, 1, 1, 0)
[0 0 1 0 1 0]
2 [[0, 1]]
[0, 1]
[0, 0, 0, 1, 0, 1]
(0, 1, 1, 1, 0, 0)
[0 1 1 0 0 1]
2 [[0, 1]]
[0, 1]
[1, 1, 1, 0, 1, 0]
(1, 0, 1, 0, 1, 0)
[0 1 0 0 0 0]
Hello
2 [[0, 1]]
[0, 1]
[1, 1, 0, 1, 1, 0]
(1, 1, 0, 1, 1, 0)
[0 0 0 0 0 0]
2 [[

ValueError: need more than 1 value to unpack